stages:
  build:
    - image
  deploy:
    - cookbook
    - test
    - finish

variables:
  - name: TARGET
    value: "dev"
    description: "Target cluster to deploy to"

build:
  target:
    match:
      name: $TARGET  
  image:
    docker:
      actions:
        - action: build
          tag: $COMMIT_ID
deploy:
  target:
    match:
      name: $TARGET
  cookbook:
    async: true
    kubernetes:
      actions:
        - action: deploy
          name: cookbook
          public: true
          framework: flask
  test:
    script:
      commands:
        - echo "Testing"
  finish:
    script:
      commands:
        - echo "Finished"
